[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
backgroundColor = "#000000"
secondaryBackgroundColor = "#050510"
textColor = "#00d4ff"
font = "monospace"

[browser]
gatherUsageStats = false